### ISSUE TITLE
can't install module

### ISSUE THREAD

**Issue by mehmetserter** [danitool/openwrt-pkgs#1]
Hi,
the lirc packages build without error but insmod gives the following error:
`kmod: failed to insert /lib/modules/3.10.49/lirc_gpio_generic.ko`

the kernel is patched with "728-MIPS-ath79-add-gpio-irq.patch"

I'm using openwrt BB on ar71xx

**Comment by danitool** [comment]
Check that you're not using any gpio already used by the kernel. GPIOs for leds or buttons cannot be used by default because they are already handled by other kernel drivers.

**Comment by mehmetserter** [comment]
Thank you for your reply, It turns out I had to add dependecies (+libusb +libftdi) to lirc package as well, and kernel clean solved the issue.
